workflow:
  rules:
    - if: '$CI_EXTERNAL_PULL_REQUEST_IID'
    # Add a comment here
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: '$CI_COMMIT_TAG'

tag-only job:
  script:
    - echo "Tag creation"
    - echo "CI_COMMIT_TAG is .$CI_COMMIT_TAG."
    - echo "CI_PIPELINE_SOURCE is .$CI_PIPELINE_SOURCE."
  rules:
    - if: '$CI_COMMIT_TAG'

mini job:
  script:
    - echo "Hello world"
    - echo "CI_COMMIT_BRANCH is .$CI_COMMIT_BRANCH."
    - echo "CI_COMMIT_TAG is .$CI_COMMIT_TAG."


git action:
  rules:
    - when: never
  image: python:3.10-buster
  script:
    - pip install gitpython requests
    - mkdir -p .ssh
    - echo $GITHUB_DEPLOY_KEY | base64 -d > .ssh/deploy
    - python repo_actions.py
    - ls
    - git status
    - git remote -v
