workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"

git action:
  image: python:3.10-buster
  script:
    - pip install gitpython requests
    - mkdir -p .ssh
    - echo $GITHUB_DEPLOY_KEY | base64 -d > .ssh/deploy
    - python repo_actions.py
    - ls
    - git status
    - git remote -v
