git action:
  image: python:3.10-buster
  script:
    - python --version
    - pip install gitpython
    - mkdir -p .ssh
    - echo $GITHUB_DEPLOY_KEY | base64 -d > .ssh/deploy
    - ls -lh .ssh
    - which ssh
    - GIT_SSH="ssh -i $(realpath .ssh/deploy)" python repo_actions.py
