on:
  pull_request:
    types: [opened, edited, synchronize, reopened]


jobs:
  waste-time:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Sleeping Beauty
        run: |
          sleep 60
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: |
          echo "Hello"
