---
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches: [main, ci/**]
jobs:
  some-output:
    runs-on:
      - codebuild-spacktainers-${{ github.run_id }}-${{ github.run_attempt }}
    name: Quick test with some output
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Do something
        run: |-
          echo "Hello world"
          pwd
          ls
          ls /opt
          ls /opt/spack/*
          echo "All done"
