---
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches: [main, ci/**]
jobs:
  some-output:
    runs-on:
      - codebuild-personal-repo-test-${{ github.run_id }}-${{ github.run_attempt }}
    name: Quick test with some output
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Do something
        run: |-
          echo "Hello world"
          pwd
          ls
          ls /opt
          ls /opt/spack/*
          echo "All done. Really"
      - name: Write to file
        run: |-
          echo "Hello world" > /tmp/output.log
          pwd >> /tmp/output.log
          ls >> /tmp/output.log
          ls /opt >> /tmp/output.log
          ls /opt/spack/* >> /tmp/output.log
          echo "All done" >> /tmp/output.log
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-log
          path: /tmp/output.log
